openapi: 3.0.3
info:
  title: API Ping
  version: 1.0.0

paths:
  /ping:
    get:
      summary: Vérifie la disponibilité de l'API
      responses:
        '200':
          description: Réponse réussie
          content:
            text/plain:
              schema:
                type: string
                example: "pong"
