openapi: 3.0.3
info:
  title: API Utilisateurs
  version: 1.0.0

paths:
  /users:
    get:
      summary: Récupérer une liste d'utilisateurs
      parameters:
        - name: page
          in: query
          description: Numéro de la page à récupérer
          required: false
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          description: Nombre d'utilisateurs par page
          required: false
          schema:
            type: integer
            example: 20
      responses:
        '200':
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        '400':
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
