openapi: 3.0.3
info:
  title: API Gestion de Tâches
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Récupérer toutes les tâches
      responses:
        '200':
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
                - id: 2
                  title: "Réviser l'examen"
                  completed: true

    post:
      summary: Créer une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
            example:
              - title: "Apprendre OAS3"
                completed: false
              - title: "Aller au sport"
                completed: false
      responses:
        '201':
          description: Liste des tâches nouvellement créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      summary: Récupérer une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche introuvable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Task not found"

    delete:
      summary: Supprimer une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Tâche introuvable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Task not found"

  /tasks:
    delete:
      summary: Supprimer une liste de tâches par IDs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
            example: [1, 2, 3]
      responses:
        '200':
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Faire les courses"
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
